version: '3.8'

volumes:
  nextcloud-docroot:

services:

  nextcloud:
    image: nextcloud:24-apache
    restart: always
    networks:
      - nextcloud-network
    ports:
      - 8077:80
    volumes:
      - nextcloud-docroot:/var/www/html
    environment:
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - MYSQL_PASSWORD=${pass}
      - MYSQL_DATABASE=postgres
      - MYSQL_USER=${user}
      - MYSQL_HOST=postgres

networks:
  nextcloud-network:
    external: true
