version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${root_password}
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=${user}
      - MYSQL_PASSWORD=${user_password}
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
#    networks: 
#    - sprint

#networks:
#  sprint:
#    name: sprint
#    driver: bridge