version: '3'
services:
  python:
    image: python
    restart: always
    volumes:
      - /etc/sprint/python:/tmp/test
#    command:
#      - cd /tmp/test
#      - bash /tmp/test/requirements.sh
#      - sh /tmp/test/shell.sh
    entrypoint: 
      - sleep 5000
      - bash
    networks:
    - nextcloud-network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  nextcloud-network:
    external: true
