version: '3'
services:
  python:
    image: python
    restart: always
    volumes:
      - /etc/sprint/python:/root/pcode
    entrypoint:
      - bash /root/pcode/requirements.sh
      - sh /root/pcode/shell.sh
    networks:
    - nextcloud-network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  nextcloud-network:
    external: true
