version: '3'
services:
  python:
    image: python
    restart: always
    volumes:
      - /etc/sprint/python:/root/pcode
    command:
      - bash /etc/sprint/python/requirements.sh
      - sh /etc/sprint/python/shell.sh
    networks:
    - nextcloud-network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  nextcloud-network:
    external: true
