version: '3'
volumes:
  data:
services:
  python:
    image: python
    restart: always
#    entrypoint: bash
    environment:
      - /root/pcode/code.py=/root/pcode/code.py
    command: "/root/pcode/code.py"
    networks:
    - nextcloud-network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  nextcloud-network:
    external: true
