version: '3'
#volumes:
#  data:
services:
  python:
    image: python
    restart: always
    volumes:
      - /root/pcode/=/root
#    command: "/root/pcode/app.py"
    entrypoint: /root/shell.sh
    networks:
    - nextcloud-network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  nextcloud-network:
    external: true
