version: '3'
#volumes:
#  data:
services:
  python:
    image: python
    restart: always
    volumes:
      - /etc/sprint/python:/app
#    command: "/root/pcode/app.py"
#    environment:
#      - $PATH=/root
    entrypoint: sh /app/app.py
    networks:
    - nextcloud-network

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  nextcloud-network:
    external: true
