version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=david
      - POSTGRES_PASSWORD=david
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - nextcloud-network
volumes:
  db:
    driver: local

networks:
  nextcloud-network:
    external: true