version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${puser}
      - POSTGRES_PASSWORD=${ppass}
    ports:
      - '5432:5432'
    volumes: 
      - db2:/var/lib/postgresql/data
    networks:
      - nextcloud-network
    user: ${john}
volumes:
  db:
    driver: local

networks:
  nextcloud-network:
    external: true