version: '3.8'
services:
  db:
    image: docker.io/bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRES_USER=${puser}
      - POSTGRES_PASSWORD=${ppass}
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_DATABASE=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - nextcloud-network
#    user: ${john}
volumes:
  db:
    driver: local

networks:
  nextcloud-network:
    external: true