version: '3'
volumes:
  data:
services:
  slave:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    environment:
      - MYSQL_ROOT_PASSWORD=${root_password}
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=${user}
      - MYSQL_PASSWORD=${user_password}
      - MYSQL_INITDB_SKIP_TZINFO=Y
    
    volumes:
      - data:/var/lib/mysql
      - /root/config-files/secondary/secondary-1.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3307:3306"
    networks:
    - nextcloud-network
    links:
    - db

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODENAME}

networks:
  nextcloud-network:
    external: true
